name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
 
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.TORLIB_SECRET }}
      run: |
        apt-get update
        apt-get install -y git
        git clone "https://token:${TORLIB_SECRET}@github.com/${GITHUB_REPOSITORY}.git" .
        git checkout v0.0.4_documentation
        apt-get install -y python3-pip
        pip3 install .
      shell: bash
 
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.TORLIB_SECRET }}
      run: |
        chmod +x docs/buildDocs.sh
        docs/buildDocs.sh
      shell: bash
